version: '3.1'

services:

  wordpress-fun:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db-fun
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - wordpress_data:/var/www/html
      - ../examples/wordpress-plugin/:/usr/src/wordpress/wp-content/plugins/php-fun-plugin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/wp-admin/install.php"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      db-fun:
        condition: service_healthy

  db-fun:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    healthcheck:
      test: ["CMD", "mysqladmin" , "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql

  cli-fun:
    image: wordpress:cli
    user: "33:33"
    environment:
      WORDPRESS_DB_HOST: db-fun
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress_db
    command: tail -f /dev/null
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      db-fun:
        condition: service_healthy
      wordpress-fun:
        condition: service_healthy

volumes:
  db_data:
  wordpress_data:
